// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgtitrqecuzpbzignqoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndGl0cnFlY3V6cGJ6aWducW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjM5MDIsImV4cCI6MjA3Mjc5OTkwMn0.OKGpKs4Oznh8V1CZI6qK1uPKevrQknCeB5MbR70E0ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});